conda activate moe-adaptors
export CUDA_VISIBLE_DEVICES=0

# python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -adaptor_input attention -expert_type gnn -dataset cola -gate_type gumbel  -output_dir output/glue/roberta/moe_gnn_gumbel_cola_prune_gates_attn/ -prune_gates -per_device_train_batch_size 4 -gradient_accumulation_steps 16 2>&1 | tee glue_roberta_moe_gnn_gumbel_cola_prune_gates_attn.out
# python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -adaptor_input attention -expert_type gnn -dataset mrpc -gate_type gumbel  -output_dir output/glue/roberta/moe_gnn_gumbel_mrpc_prune_gates_attn/ -prune_gates -per_device_train_batch_size 4 -gradient_accumulation_steps 16 2>&1 | tee glue_roberta_moe_gnn_gumbel_mrpc_prune_gates_attn.out
# python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -adaptor_input attention -expert_type gnn -dataset rte -gate_type gumbel  -output_dir output/glue/roberta/moe_gnn_gumbel_rte_prune_gates_attn/ -prune_gates -per_device_train_batch_size 4 -gradient_accumulation_steps 16 2>&1 | tee glue_roberta_moe_gnn_gumbel_rte_prune_gates_attn.out
# python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -adaptor_input attention -expert_type gnn -dataset stsb -gate_type gumbel  -output_dir output/glue/roberta/moe_gnn_gumbel_stsb_prune_gates_attn/ -prune_gates -per_device_train_batch_size 4 -gradient_accumulation_steps 16 2>&1 | tee glue_roberta_moe_gnn_gumbel_stsb_prune_gates_attn.out
# python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -adaptor_input attention -expert_type gnn -dataset sst2 -gate_type gumbel  -output_dir output/glue/roberta/moe_gnn_gumbel_sst2_prune_gates_attn/ -prune_gates -per_device_train_batch_size 4 -gradient_accumulation_steps 16 2>&1 | tee glue_roberta_moe_gnn_gumbel_sst2_prune_gates_attn.out
python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -adaptor_input attention -expert_type gnn -dataset qnli -gate_type gumbel  -output_dir output/glue/roberta/moe_gnn_gumbel_qnli_prune_gates_attn/ -prune_gates -per_device_train_batch_size 4 -gradient_accumulation_steps 16 2>&1 | tee glue_roberta_moe_gnn_gumbel_qnli_prune_gates_attn.out
# python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -adaptor_input attention -expert_type gnn -dataset mnli -gate_type gumbel  -output_dir output/glue/roberta/moe_gnn_gumbel_mnli_prune_gates_attn/ -prune_gates -per_device_train_batch_size 4 -gradient_accumulation_steps 16 2>&1 | tee glue_roberta_moe_gnn_gumbel_mnli_prune_gates_attn.out
# python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -adaptor_input attention -expert_type gnn -dataset qqp -gate_type gumbel  -output_dir output/glue/roberta/moe_gnn_gumbel_qqp_prune_gates_attn/ -prune_gates -per_device_train_batch_size 4 -gradient_accumulation_steps 16 2>&1 | tee glue_roberta_moe_gnn_gumbel_qqp_prune_gates_attn.out
