conda activate moe-adaptors
export CUDA_VISIBLE_DEVICES=3

python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -expert_type gnn -dataset cola -gate_type gumbel -tau_decay -terminal_tau 0.5 -output_dir output/glue/roberta/moe_gnn_gumbel_cola_cls_decay2/ -plot_gates 2>&1 | tee glue_roberta_moe_gnn_gumbel_cola_cls_decay2.out
python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -expert_type gnn -dataset mrpc -gate_type gumbel -tau_decay -terminal_tau 0.5 -output_dir output/glue/roberta/moe_gnn_gumbel_mrpc_cls_decay2/ -plot_gates 2>&1 | tee glue_roberta_moe_gnn_gumbel_mrpc_cls_decay2.out
python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -expert_type gnn -dataset rte -gate_type gumbel -tau_decay -terminal_tau 0.5 -output_dir output/glue/roberta/moe_gnn_gumbel_rte_cls_decay2/ -plot_gates 2>&1 | tee glue_roberta_moe_gnn_gumbel_rte_cls_decay2.out
python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -expert_type gnn -dataset stsb -gate_type gumbel -tau_decay -terminal_tau 0.5 -output_dir output/glue/roberta/moe_gnn_gumbel_stsb_cls_decay2/ -plot_gates 2>&1 | tee glue_roberta_moe_gnn_gumbel_stsb_cls_decay2.out
python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -expert_type gnn -dataset sst2 -gate_type gumbel -tau_decay -terminal_tau 0.5 -output_dir output/glue/roberta/moe_gnn_gumbel_sst2_cls_decay2/ -plot_gates 2>&1 | tee glue_roberta_moe_gnn_gumbel_sst2_cls_decay2.out
python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -expert_type gnn -dataset qnli -gate_type gumbel -tau_decay -terminal_tau 0.5 -output_dir output/glue/roberta/moe_gnn_gumbel_qnli_cls_decay2/ -plot_gates 2>&1 | tee glue_roberta_moe_gnn_gumbel_qnli_cls_decay2.out
python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -expert_type gnn -dataset mnli -gate_type gumbel -tau_decay -terminal_tau 0.5 -output_dir output/glue/roberta/moe_gnn_gumbel_mnli_cls_decay2/ -per_device_train_batch_size 4 -gradient_accumulation_steps 16 -plot_gates 2>&1 | tee glue_roberta_moe_gnn_gumbel_mnli_cls_decay2.out
python main.py -plm_name roberta-base -freeze_plm -pooling_method cls -adator_type moe -expert_type gnn -dataset qqp -gate_type gumbel -tau_decay -terminal_tau 0.5 -output_dir output/glue/roberta/moe_gnn_gumbel_qqp_cls_decay2/ -plot_gates 2>&1 | tee glue_roberta_moe_gnn_gumbel_qqp_cls_decay2.out
